import assert from "node:assert/strict";
import {isFoundryFolder, isVideo, mapIdentity, nameScore, rankImports, mediaForImport, matchingOverlays, scanRoot, uncoveredVariants} from "../dist/scripts/matching.js";
const train = "maps/Cybermaps_Train Assault 35x19 4K - Gridless.jpg";
const trainVideo = "maps/Cybermaps_Train Assault 35x19 4K.mp4";
const trainZoom = "maps/Cybermaps_Train Assault 71x40 4K Zoomed Out - Gridless.jpg";
const trainZoomVideo = "maps/Cybermaps_Train Assault 71x40 4K Zoomed Out.mp4";
const train8k = "maps/Cybermaps_Train Assault 35x19 8K - Gridless.jpg";
const item = path => ({path,kind:"Foundry Scene",data:{}});
const regular = item("maps/foundry walls/fvtt-train-assault.json"), zoom = item("maps/foundry walls/fvtt-train-assault-zoomed-out.json");
assert.equal(mapIdentity(train),"train assault");
assert.equal(mapIdentity(trainZoom),"train assault zoomout");
assert.equal(rankImports([zoom,regular],train)[0].item,regular);
assert.equal(rankImports([regular,zoom],trainZoom)[0].item,zoom);
assert.equal(nameScore(train,trainZoom),0);
assert.equal(nameScore(train,trainZoom,true),100);
for (const folder of ["Foundry","FOundry Walls","FoundryWalls","FoundryScenes","foundry scenes"]) assert.equal(isFoundryFolder(`maps/${folder}`),true);
assert.equal(isFoundryFolder("maps/props 4K"),false);
assert.equal(scanRoot("maps/Train/Image"),"maps/Train");
assert.equal(scanRoot("maps/Train/Video"),"maps/Train");
assert.equal(scanRoot("maps/Train"),"maps/Train");
assert.deepEqual(mediaForImport(regular,train,[train8k,train,trainVideo,trainZoom,trainZoomVideo],false),[train,train8k]);
assert.deepEqual(mediaForImport(zoom,train,[train,trainVideo,trainZoom,trainZoomVideo],true),[trainZoomVideo]);
// Generic Scene names must not override the layout encoded in the JSON filename.
assert.deepEqual(mediaForImport({...zoom,data:{name:"Train Assault"}},train,[train,trainVideo,trainZoom,trainZoomVideo],false),[trainZoom]);
const eatery1 = "maps/SOL-CorporateEateryInt-Map1-128px-4k.webp";
const eatery1Video = "maps/SOL-CorporateEateryInt-Map1-128px-VTT4k.webm";
const eatery2 = "maps/SOL-CorporateEateryInt-Map2-128px-4k.webp";
const floor1 = item("maps/FoundryScenes/fvtt-Scene-corporate-eatery-interior-floor-1-BwEiKlwvnmTponYX.json");
const floor2 = item("maps/FoundryScenes/fvtt-Scene-corporate-eatery-interior-floor-2-mGUminkAD0MB4hn5.json");
assert.equal(mapIdentity(floor1.path),"corporate eatery interior floor1");
assert.equal(mapIdentity(eatery1),"corporate eatery interior floor1");
assert.equal(rankImports([floor2,floor1],eatery1)[0].item,floor1);
assert.equal(nameScore(eatery1,eatery2),0);
assert.equal(nameScore(eatery1,eatery2,true),100);
assert.deepEqual(mediaForImport(floor1,eatery1,[eatery2,eatery1,eatery1Video],true),[eatery1Video]);
const overlay = "maps/SOL-CorporateEateryInt-Map1-OVERLAY-128px-4k.webp";
const overlayVideo = "maps/SOL-CorporateEateryInt-Map1-OVERLAY-128px-VTT4k.webm";
const wrongOverlay = "maps/SOL-CorporateEateryInt-Map2-Foreground-128px-4k.webp";
assert.deepEqual(new Set(matchingOverlays(eatery1,[overlay,overlayVideo,wrongOverlay,eatery1])),new Set([overlay,overlayVideo]));
assert.equal(matchingOverlays(train,["maps/Unrelated-Foreground.webp"]).length,0);
assert.equal(isVideo(eatery1Video),true);
assert.deepEqual(uncoveredVariants(eatery1,[],[eatery1,eatery1Video,eatery2,overlay]),[eatery2]);
assert.deepEqual(uncoveredVariants(eatery1,[floor1,floor2],[eatery1,eatery1Video,eatery2,overlay]),[]);
console.log("Screenshot filename mappings, distinct layouts, media pairs, and overlay exclusions passed.");
